config/routes.rb
Spree::Core::Engine.routes.append do
  resources :orders do
    resource :checkout, :controller => 'checkout' do
      member do
        get :payone_success
        get :payone_error
        get :payone_back
      end
    end
  end

  namespace :admin do
    resources :orders do
      resources :payments do
        member do
          get :payone_success
          get :payone_error
          get :payone_back
        end
      end
    end

    resource :payone_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :payone_logs do
      collection do
        get :clear
      end
    end

    resource :payone_docs, only: :show
  end
end

app/models/spree/payone_log.rb
# Provides PAYONE LOG model. It is used to store logs.
module Spree
  class PayoneLog < ActiveRecord::Base
    # we must run logger within new connection to avoid changes to be rollbacked
    # for details see: state_machine documentation
    establish_connection Rails.env.to_sym

    #attr_accessible :level, :message
  end
end

app/controllers/spree/admin/payone_logs_controller.rb
module Spree
  module Admin
    class PayoneLogsController < ResourceController
      def index
        respond_with(@collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end
      
      def clear
        Spree::PayoneLog.destroy_all
        respond_with(@collection) do |format|
          format.html { redirect_to collection_url }
          format.json { render :json => json_data }
        end
      end
      
      protected

        def collection
          return @collection if @collection.present?
          
          # Use default sort by created_at desc if not provided
          params[:q] = {} unless params.has_key?(:q)
          if !params[:q].has_key?(:s) || (params[:q].has_key?(:s) && params[:q][:s].to_s.empty?)
            params[:q][:s] = "created_at desc"
          end
          
          unless request.xhr?
            @search = Spree::PayoneLog.search(params[:q])
            @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_products_per_page])
          else
            @collection = Spree::PayoneLog.
                              where("spree_payone_logs.message #{LIKE} :search
                                     OR spree_payone_logs.level #{LIKE} :search",
              { :search => "#{params[:q].strip}%" }).
                limit(params[:limit] || 100)
          end
        end

      private
        
        # Allows different formats of json data to suit different ajax calls.
        def json_data
          json_format = params[:json_format] or 'default'
          case json_format
          when 'basic'
            collection.map { |u| { 'id' => u.id, 'name' => u.message } }.to_json
          else
            collection.to_json(:only => [:id, :level, :message])
          end
        end
    end
  end
end

app/views/spree/admin/payone_logs/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:listing_payone_logs) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:clear_payone_logs), clear_admin_payone_logs_url, :icon => 'icon-trash', :id => 'admin_clear_payone_logs_link' %>
  </li>
<% end %>

<div class="alpha twelve columns">
  <%= search_form_for [:admin, @search] do |f| %>
    <fieldset class="no-border-bottom" id="logging-preferences" data-hook>
      <legend align="center"> <%= Spree.t(:search) %> </legend>
      <div data-hook="admin_payone_logs_index_search">
        <div class="alpha twelve columns">
            <%= t(:payone_log_message) %>:
            <%= f.text_field :message_cont, :size =>'75%' %>
        </div>
        <div class="clear"></div>
        <fieldset class="no-border-top">
          <div class="form-buttons actions filter-actions " data-hook="admin_payone_logs_index_search_buttons">
            <%= button Spree.t(:search), 'icon-search' %>
          </div>
        </fieldset>
      </div>
    </fieldset>
  <% end %>
</div>

<%= paginate @payone_logs %>

<% if !Spree::Config[:payone_db_logging_enabled] %>
  <div class="alpha twelve columns no-objects-found">
    <%= t(:payone_db_logging_disabled) %>
  </div>
<% end %>

<table class="index" id="listing_payone_logs" data-hook>
  <colgroup>
    <col style="width: 10%">
    <col style="width: 50%">
    <col style="width: 30%">
    <col style="width: 10%">
  </colgroup>
  <thead>
    <tr data-hook="admin_payone_logs_index_headers">
      <th><%= sort_link @search, :level, t(:payone_log_level), {:default_order => "desc"}, {:title => t(:payone_log_level_title)} %></th>
      <th><%= sort_link @search, :message, t(:payone_log_message), {:default_order => "desc"}, {:title => t(:payone_log_message_title)} %></th>
      <th><%= sort_link @search, :created_at, t(:payone_log_created_at), {:default_order => "desc"}, {:title => t(:payone_log_created_at_title)} %></th>
      <th data-hook="admin_payone_logs_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @payone_logs.each do |payone_log|%>
      <tr id="<%= spree_dom_id payone_log %>" data-hook="admin_payone_logs_index_rows" class="<%= cycle('odd', 'even')%>">
        <td class='payone_log_level'><%=link_to payone_log.level, object_url(payone_log) %></td>
        <td class='payone_log_message'><%= simple_format(payone_log.message) %></td>
        <td class='payone_log_created_at'><%= payone_log.created_at %></td>
        <td data-hook="admin_payone_logs_index_row_actions" class="actions">
          <%= link_to_delete payone_log, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @payone_logs %>

app/views/spree/admin/payone_logs/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:payone_log) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_payone_logs), collection_url, :icon => 'icon-arrow-left', :id => 'admin_clear_payone_logs_link' %>
  </li>
<% end %>

<table>
  <tr data-hook="payone_log_level">
    <th><%= t(:payone_log_level) %></th>
    <td>
      <%= @payone_log.level %>
    </td>
  </tr>
  <tr data-hook="payone_log_message">
    <th><%= t(:payone_log_message) %></th>
    <td>
      <%= @payone_log.message %>
    </td>
  </tr>
  <tr data-hook="payone_log_created_at">
    <th><%= t(:payone_log_created_at) %></th>
    <td>
      <%= @payone_log.created_at %>
    </td>
  </tr>
</table>