config/routes.rb
Spree::Core::Engine.routes.append do
  resources :orders do
    resource :checkout, :controller => 'checkout' do
      member do
        get :payone_success
        get :payone_error
        get :payone_back
      end
    end
  end

  namespace :admin do
    resources :orders do
      resources :payments do
        member do
          get :payone_success
          get :payone_error
          get :payone_back
        end
      end
    end

    resource :payone_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :payone_logs do
      collection do
        get :clear
      end
    end

    resource :payone_docs, only: :show
  end
end

app/controllers/spree/admin/payone_settings_controller.rb
module Spree
  module Admin
    class PayoneSettingsController < BaseController
      def init_preferences
        @redirect_url_preferences = {
          :payone_engine_host => {}
        }

        @logging_preferences = {
          :payone_db_logging_enabled => {},
          :payone_file_logging_enabled => {}
        }
      end

      def show
        init_preferences
      end

      def edit
        init_preferences
      end

      def update
        params.each do |name, value|
          next unless Spree::Config.has_preference? name
          Spree::Config[name] = value
        end

        redirect_to admin_payone_settings_path
      end

      def dismiss_alert
        if request.xhr? and params[:alert_id]
          dismissed = Spree::Config[:dismissed_spree_alerts] || ''
          Spree::Config.set :dismissed_spree_alerts => dismissed.split(',').push(params[:alert_id]).join(',')
          filter_dismissed_alerts
          render :nothing => true
        end
      end
    end
  end
end

app/helpers/spree/admin/payone_settings_helper.rb
module Spree
  module Admin
    module PayoneSettingsHelper

      def payone_settings_preference_field_tag(name, value, options)
        preference_field_tag(name, value, options)
      end

      def payone_settings_preference_visible_value(value, options)
        case options[:type]
        when :boolean
          value = value ? t(:yes) : t(:no)
        when :string
            if options.has_key? :values
              options[:values].each do |element|
                if element.kind_of?(Array) && element.length > 1 && element[1].to_s == value.to_s
                  value = t(element[0])
                end
              end
            end
        end
        value
      end
    end
  end
end

app/views/spree/admin/payone_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<% content_for :page_title do %>
  <%= t(:edit_payone_settings) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_payone_settings), admin_payone_settings_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= form_tag admin_payone_settings_path, :method => :put do %>
  <div class="alpha twelve columns">
    <fieldset class="no-border-bottom" id="logging-preferences" data-hook>
      <legend align="center"> <%= t(:logging_preferences) %> </legend>
      <% @logging_preferences.each do |key, options|
        type = Spree::Config.preference_type(key) %>
        <%= label_tag(key, t(key) + ': ') %>
        <%= payone_settings_preference_field_tag(key, Spree::Config[key], options.merge!(:type => type)) %>
        <br>
      <% end %>
    </fieldset>

    <fieldset class="no-border-bottom" id="logging-preferences" data-hook>
      <legend align="center"> <%= t(:redirect_url_preferences) %></legend>
      <% @redirect_url_preferences.each do |key, options|
        type = Spree::Config.preference_type(key) %>
        <%= label_tag(key, t(key) + ': ') + tag(:br) %>
        <%= payone_settings_preference_field_tag(key, Spree::Config[key], options.merge!(:type => type)) %>
      <% end %>
    </fieldset>

    <fieldset class="no-border-top" id="logging-preferences" data-hook>
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'icon-refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= button_link_to Spree.t('actions.cancel'), admin_payone_settings_url, :icon => 'icon-remove' %>
      </div>
    </fieldset>
  </div>
<% end %>

app/views/spree/admin/payone_settings/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:payone_settings) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:edit_payone_settings), edit_admin_payone_settings_path, icon: 'icon-edit', :id => 'admin_edit_payone_setting_link' %>
  </li>
<% end %>

<table class="index" data-hook="preferences">
  <thead>
    <tr>
      <th colspan="2" style="font-size: 150%"><%= t(:redirect_url_preferences) %></th>
    </tr>
  </thead>
  <tbody>
    <% @redirect_url_preferences.each do |key, options|
      type = Spree::Config.preference_type(key) %>
      <tr>
        <th scope="row"><%= t(key) %>:</th>
        <td><%= payone_settings_preference_visible_value(Spree::Config[key], options.merge!(:type => type)) %></td>
      </tr>
    <% end %>
  </tbody>

  <thead>
    <tr>
      <th colspan="2" style="font-size: 150%"><%= t(:logging_preferences) %></th>
    </tr>
  </thead>
  <tbody>
    <% @logging_preferences.each do |key, options|
      type = Spree::Config.preference_type(key) %>
      <tr>
        <th scope="row"><%= t(key) %>:</th>
        <td><%= payone_settings_preference_visible_value(Spree::Config[key], options.merge!(:type => type)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>