config/routes.rb
Spree::Core::Engine.routes.append do
  resources :orders do
    resource :checkout, :controller => 'checkout' do
      member do
        get :payone_success
        get :payone_error
        get :payone_back
      end
    end
  end

  namespace :admin do
    resources :orders do
      resources :payments do
        member do
          get :payone_success
          get :payone_error
          get :payone_back
        end
      end
    end

    resource :payone_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :payone_logs do
      collection do
        get :clear
      end
    end

    resource :payone_docs, only: :show
  end
end

app/views/spree/admin/shared/_configuration_menu_payone_extension.html.erb
<%= configurations_sidebar_menu_item t(:payone_settings), admin_payone_settings_path %>
<%= configurations_sidebar_menu_item t(:payone_logs), admin_payone_logs_path %>
<%= configurations_sidebar_menu_item t(:payone_docs), admin_payone_docs_path %>

app/views/spree/admin/shared/_tabs.html.erb
<% if can? :admin, Spree::Order %>
  <%= tab :orders, :payments, :creditcard_payments, :shipments, :credit_cards, :return_authorizations, :match_path => '/orders', :icon => 'icon-shopping-cart' %>
<% end %>
<% if can? :admin, Spree::Product %>
  <%= tab :products, :option_types, :properties, :prototypes, :variants, :product_properties, :icon => 'icon-th-large' %>
<% end %>
<% if can? :admin, Spree::Admin::ReportsController %>
  <%= tab :reports, :icon => 'icon-file'  %>
<% end %>
<%= tab :configurations, :general_settings, :mail_methods, :image_settings, :tax_categories, :tax_rates, :tax_settings, :zones, :countries, :states, :payment_methods, :taxonomies, :shipping_methods, :shipping_categories, :stock_transfers, :stock_locations, :trackers, :payone_settings, :payone_logs, :payone_docs, :label => 'config', :icon => 'icon-wrench', :url => spree.edit_admin_general_settings_path %>
<% if can? :admin, Spree::Promotion %>
  <%= tab(:promotions, :url => spree.admin_promotions_path, :label => 'promo', :icon => 'icon-bullhorn') %>
<% end %>